### ISSUE TITLE
Import wallet

### ISSUE THREAD

**Issue by n0n0n0n0** [blocktrail/wallet-recovery-tool#5]
Are there any options to import blocktrail wallet to, for example, electrum/etc?

**Comment by rubensayshi** [comment]
we've launched a feature on the web wallet last week to import BIP44 wallets (Blockchain.info, Mycelium), both the BTC and BCC wallet have this option in "Settings" now.

**Comment by n0n0n0n0** [comment]
I dont see this option in developer panel. Can i do this via API?

**Comment by n0n0n0n0** [comment]
i want to export blocktrail wallet and import it to electrum
